In [1]:
import numpy as np

EXERCISE 1

In [2]:
#INPUT VARIABLES
#num_of_student == m
#num_of_assesment == n
num_of_student = int(input("Input number of student: "))
num_of_assesment = int(input("Input number of assesment: "))

#GENERATED ARRAY SCORE
arrScore = np.random.randint(0, 101, size=(num_of_student, num_of_assesment))
print("Student Exam Scores:")
print(arrScore, "\n")

#GENERATED ARRAY Weight of Assesment
weightOfAssesment = np.random.randint(0,10, size=(1, num_of_assesment))
print("Contents of weightOfAssesment array for the first time:",weightOfAssesment)
weightOfAssesment = weightOfAssesment*10
print("Contents of weightOfAssesment array after being multiplied:",weightOfAssesment)

#TOTAL WEIGHT OF ASSESMENT ELEMENT IS 1
totalWoS = np.sum(weightOfAssesment)

#NORMALIZE WEIGHT OF ASSESMENT
normalizeWoS = weightOfAssesment/totalWoS
arrHasil = np.round(normalizeWoS, decimals=2)
print("Contents of weightOfAssesment array for the last time:",arrHasil)
print()


Student Exam Scores:
[[76 85 82]
 [ 5  4 96]
 [ 7 91 24]] 

Contents of weightOfAssesment array for the first time: [[3 5 8]]
Contents of weightOfAssesment array after being multiplied: [[30 50 80]]
Contents of weightOfAssesment array for the last time: [[0.19 0.31 0.5 ]]



In [3]:
#CALCULATED THE FINAL SCORE
finalScore = np.array(arrHasil*arrScore)
print("Final score:\n",finalScore)
finalScoreReshape = finalScore.reshape(-1,1)
print("Final score after reshape:\n",finalScoreReshape)
print("Array size after reshape:",finalScoreReshape.shape)

Final score:
 [[14.44 26.35 41.  ]
 [ 0.95  1.24 48.  ]
 [ 1.33 28.21 12.  ]]
Final score after reshape:
 [[14.44]
 [26.35]
 [41.  ]
 [ 0.95]
 [ 1.24]
 [48.  ]
 [ 1.33]
 [28.21]
 [12.  ]]
Array size after reshape: (9, 1)


In [4]:
#CONCATENATE
studentScore = np.concatenate([arrScore, finalScore], axis=1)
print("List of student score: ")
print(studentScore)

#AVERAGE SCORE
averageScore = np.average(arrScore, axis=0)
print("Average score:",averageScore)

#NUMBER OF STUDENTS WHO SCORED <55
scoreUnder55 = np.sum(arrScore < 55)
print("Number of students who scored < 55:",scoreUnder55)

List of student score: 
[[76.   85.   82.   14.44 26.35 41.  ]
 [ 5.    4.   96.    0.95  1.24 48.  ]
 [ 7.   91.   24.    1.33 28.21 12.  ]]
Average score: [29.33333333 60.         67.33333333]
Number of students who scored < 55: 4


In [5]:
sortDesc = np.sort(studentScore, axis=0)[::-1, ::]
print("List of student score in descending order:\n",sortDesc)

List of student score in descending order:
 [[76.   91.   96.   14.44 28.21 48.  ]
 [ 7.   85.   82.    1.33 26.35 41.  ]
 [ 5.    4.   24.    0.95  1.24 12.  ]]
