In [50]:
import numpy as np

In [51]:
p = int(input("Masukkan jumlah produk: "))
k = int(input("Masukkan jumlah kriteria penilaian: "))

arrRating = np.random.randint(1,6, size=(p,k))
print("Isi arrRating:\n",arrRating)

weightOfCriteria = 10 *(np.random.randint(1,11, size=(1,k)))
print("Weight Of Criteria: ",weightOfCriteria)
totalWeight = np.sum(weightOfCriteria)
print("Total weight: ",totalWeight)
normalizeWOC = np.round(weightOfCriteria/totalWeight, 2)
print("Normalize WOC: ",normalizeWOC)
print("Normalize WOC size: ",normalizeWOC.size)

finalRating = np.sum(np.array(arrRating*normalizeWOC), axis=1)
print("Final rating before reshape: ",finalRating)
finalRating = finalRating.reshape(p,1)
print("Final rating after reshape: \n",finalRating)
print("Final rating size: ",finalRating.size)

productRating = np.concatenate([arrRating, finalRating], axis=1)
averageRating = np.average(productRating, axis=0)
print("Rata-rata kolom: \n", averageRating)
print("Jumlah produk yang ratingnya di bawah 3.0:\n", np.sum(productRating < 3.0))



Isi arrRating:
 [[1 5 2 5 2 3 3 1 2 2 2 2]
 [4 4 3 4 1 4 5 2 3 5 4 5]
 [5 5 4 5 5 5 1 5 4 3 1 2]
 [2 4 1 1 2 3 5 3 1 4 3 3]
 [1 2 1 3 3 4 3 4 3 2 3 4]
 [4 4 3 4 5 2 3 4 2 3 2 5]
 [3 4 1 4 3 4 1 1 1 4 3 4]
 [1 5 1 1 3 4 3 4 1 1 1 4]
 [1 3 3 1 5 4 5 1 5 4 4 5]
 [2 4 1 1 1 2 1 5 2 4 2 1]]
Weight Of Criteria:  [[ 10  50 100  70  60  80  90  90 100  30  90  70]]
Total weight:  840
Normalize WOC:  [[0.01 0.06 0.12 0.08 0.07 0.1  0.11 0.11 0.12 0.04 0.11 0.08]]
Normalize WOC size:  12
Final rating before reshape:  [2.53 3.6  3.61 2.63 2.96 3.26 2.47 2.48 3.64 2.09]
Final rating after reshape: 
 [[2.53]
 [3.6 ]
 [3.61]
 [2.63]
 [2.96]
 [3.26]
 [2.47]
 [2.48]
 [3.64]
 [2.09]]
Final rating size:  10
Rata-rata kolom: 
 [2.4   4.    2.    2.9   3.    3.5   3.    3.    2.4   3.2   2.5   3.5
 2.927]
Jumlah produk yang ratingnya di bawah 3.0:
 53


In [52]:
p = int(input("Jumlah produk yang ingin dianalisis: "))
k = int(input("Jumlah kategori pilihan: "))

arrProducts = np.random.randint(10,101, size=(p,k))
print("arrProducts: \n",arrProducts)
print("=========================")
print("Jumlah Dimensi: ", arrProducts.ndim)
print("Ukuran: ", arrProducts.shape)
print("Bentuk: ", arrProducts.size)

print("\nBAGIAN 2\n")

print("Jumlah elemen arrProducts yang di atas 80: ", np.sum(arrProducts>80))
arrAbove50 = arrProducts > 50
print("arrAbove50: \n", arrAbove50)

print("\nBAGIAN 3\n")

rataRataNilaiProduk = np.mean(arrProducts, axis=1)
print("Rata-rata Nilai produk: \n", rataRataNilaiProduk)

def is_promo(price):  
    return price < 50

arrayPromo = is_promo(rataRataNilaiProduk)
print("arrayPromo: \n", arrayPromo)

produkLayakDiskon = np.sum(arrayPromo == 1)

# atau bisa pakai
# produkLayakDiskon = np.sum(arrayPromo) --> katanya lebih pythonic
print("Jumlah produk layak diskon:",produkLayakDiskon)

print("\nBAGIAN 4\n")
urutArrayProducts = np.sort(arrProducts, axis=1)
print("Array Products yang urut: \n", urutArrayProducts)

produkRataRataTertinggi = np.sort(rataRataNilaiProduk)
print(produkRataRataTertinggi)
print("3 produk dengan rata-rata kategori tertinggi:", produkRataRataTertinggi[-3:])

isiKolomIndex1 = arrProducts[:, 1:2]
print("isiKolomIndex1:",isiKolomIndex1)

isiKolomIndex3 = arrProducts[:, 3:4]
print("isiKolomIndex3:",isiKolomIndex3)

print("\nBAGIAN 5\n")

averageScore = np.mean(arrProducts, axis=1).reshape(p,1)
print("Average Score:\n",averageScore)

fullReport = np.concatenate([arrProducts,averageScore], axis=1)
print("FULL REPORT: \n",fullReport)

print("Jumlah produk yang rata-rata di atas 75:", np.sum(averageScore>75))

# Ambil indeks urutan berdasarkan kolom terakhir (average score)
sorted_indices = np.argsort(fullReport[:, -1])[::-1]  # descending

# Gunakan fancy indexing untuk mengurutkan fullReport
sorted_fullReport = fullReport[sorted_indices]

# Tampilkan hasilnya
print(sorted_fullReport)


arrProducts: 
 [[89 21 48 11 54 98 34 77]
 [92 13 86 45 96 71 79 97]
 [53 42 21 94 20 64 47 38]
 [12 37 93 99 33 63 61 56]
 [30 63 39 77 45 49 19 83]]
Jumlah Dimensi:  2
Ukuran:  (5, 8)
Bentuk:  40

BAGIAN 2

Jumlah elemen arrProducts yang di atas 80:  10
arrAbove50: 
 [[ True False False False  True  True False  True]
 [ True False  True False  True  True  True  True]
 [ True False False  True False  True False False]
 [False False  True  True False  True  True  True]
 [False  True False  True False False False  True]]

BAGIAN 3

Rata-rata Nilai produk: 
 [54.    72.375 47.375 56.75  50.625]
arrayPromo: 
 [False False  True False False]
Jumlah produk layak diskon: 1

BAGIAN 4

Array Products yang urut: 
 [[11 21 34 48 54 77 89 98]
 [13 45 71 79 86 92 96 97]
 [20 21 38 42 47 53 64 94]
 [12 33 37 56 61 63 93 99]
 [19 30 39 45 49 63 77 83]]
[47.375 50.625 54.    56.75  72.375]
3 produk dengan rata-rata kategori tertinggi: [54.    56.75  72.375]
isiKolomIndex1: [[21]
 [13]
 [42]
 [37]
 [6

In [53]:
np.random.seed(0)

print("\nBAGIAN 1\n")

suhuMentah = np.random.randint(20,40, size=(6,8))
print("SUHU MENTAH: \n",suhuMentah)
print("Suhu Sensor pada 5 jam pertama: ")
print("Suhu sensor ke-2:\n", suhuMentah[:5, [1]])
print("Suhu sensor ke-4:\n", suhuMentah[:5, [3]])

suhu3D = suhuMentah.reshape(3,4,4)
print("SUHU 3D:\n",suhu3D)
print("Dimensi suhu3D:",suhu3D.ndim)

print("\nBAGIAN 2\n")
print("vsplit:\n",np.vsplit(suhuMentah,2))

hasilVStack = np.vstack(np.vsplit(suhuMentah,2))
print("vstack:\n",hasilVStack)

# harus reshape dulu
statusSensor = np.array([1, 0, 1, 1, 0, 1]).reshape(6, 1)
print("hstack:\n",np.hstack([statusSensor, hasilVStack]))

print("\nBAGIAN 3\n")

def status_panas(suhu):
    return "PANAS" if suhu > 35 else "NORMAL"

statusUFunc = np.frompyfunc(status_panas, 1, 1) #hanya bisa menerima 1 input dan 1 output
hasil = statusUFunc(suhuMentah.flatten())
print(hasil)

print("Jumlah data yang 'PANAS':", np.sum(hasil == "PANAS"))

print("\n BAGIAN 4\n")

print("Posisi suhu yang tepat bernilai 30:", np.where(suhuMentah == 30))

suhu1D = suhuMentah.flatten()
print("Suhu 1D:\n",suhu1D)

hasilPartition = np.partition(suhu1D,5)
print("Hasil Partition:",hasilPartition)

nilaiTerendah5 = hasilPartition[:5]
print("5 Nilai terendah:",nilaiTerendah5)

suhu1D = np.sort(suhuMentah.flatten())
posisi = np.searchsorted(suhu1D, 31.5)
print("Suhu 31.5 seharusnya dimasukkan di indeks ke-", posisi)


BAGIAN 1

SUHU MENTAH: 
 [[32 35 20 23 23 27 29 39]
 [38 24 26 32 21 26 27 34]
 [37 25 33 28 29 39 36 39]
 [25 35 35 20 38 23 37 39]
 [39 39 34 27 20 21 29 20]
 [30 23 31 38 22 20 20 24]]
Suhu Sensor pada 5 jam pertama: 
Suhu sensor ke-2:
 [[35]
 [24]
 [25]
 [35]
 [39]]
Suhu sensor ke-4:
 [[23]
 [32]
 [28]
 [20]
 [27]]
SUHU 3D:
 [[[32 35 20 23]
  [23 27 29 39]
  [38 24 26 32]
  [21 26 27 34]]

 [[37 25 33 28]
  [29 39 36 39]
  [25 35 35 20]
  [38 23 37 39]]

 [[39 39 34 27]
  [20 21 29 20]
  [30 23 31 38]
  [22 20 20 24]]]
Dimensi suhu3D: 3

BAGIAN 2

vsplit:
 [array([[32, 35, 20, 23, 23, 27, 29, 39],
       [38, 24, 26, 32, 21, 26, 27, 34],
       [37, 25, 33, 28, 29, 39, 36, 39]]), array([[25, 35, 35, 20, 38, 23, 37, 39],
       [39, 39, 34, 27, 20, 21, 29, 20],
       [30, 23, 31, 38, 22, 20, 20, 24]])]
vstack:
 [[32 35 20 23 23 27 29 39]
 [38 24 26 32 21 26 27 34]
 [37 25 33 28 29 39 36 39]
 [25 35 35 20 38 23 37 39]
 [39 39 34 27 20 21 29 20]
 [30 23 31 38 22 20 20 24]]
hstack:
 