WEEK 8: NUMPY

In [ ]:
import numpy as np

ok


RANDOM METHOD USING NUMPY

In [ ]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))
print(x1)
print(x2)
print(x3)

ARRAY 3D

In [2]:
A= [
    [[12,-1,10,1,1],[20,0,-2,4,16],[20,-10,10,20,60]],
    [[12,-1,10,1,1],[20,0,-2,4,16],[20,-10,1000,20,60]],
    [[12,-1,10,1,1],[20,0,-2,4,16],[20,-10,10,20,60]]
    ]

# Akses angka 1000
print(A[1][2][2])

1000


In [5]:
A = [2,-1,0,100,6]
print(A)
print(type(A))

A = np.array(A)
print(A)
print(type(A))

[2, -1, 0, 100, 6]
<class 'list'>
[  2  -1   0 100   6]
<class 'numpy.ndarray'>


In [37]:
A = [12,-1,10,1,1],[20,0,-2,4,16],[20,-10,10,20,60]
print(A, "\n")

# array menggunakan numpy
A = np.array(A)
print(A, "\n")

# row index 1-2, column index 1-3
b = A[1:3, 1:4]
print(b,"\n")

# row index 1-akhir, column index 1-3
b = A[1:, 1:4]
print(b,"\n")

# semua row, column index 1-4 terbalik
c = A[:, -1:-5:-1]
print(c,"\n")

# semua row, kolom terakhir = 1
A[:, -1]=1
print(A)
print(type(A))
print(A.dtype)
print("row: ", A.shape[0])
print("col: ", A.shape[1])
print(A.itemsize) #1 int butuh 4 byte
print("Total byte yang digunakan array A:",A.nbytes) #melihat total byte yang digunakan di memory

([12, -1, 10, 1, 1], [20, 0, -2, 4, 16], [20, -10, 10, 20, 60]) 

[[ 12  -1  10   1   1]
 [ 20   0  -2   4  16]
 [ 20 -10  10  20  60]] 

[[  0  -2   4]
 [-10  10  20]] 

[[  0  -2   4]
 [-10  10  20]] 

[[  1   1  10  -1]
 [ 16   4  -2   0]
 [ 60  20  10 -10]] 

[[ 12  -1  10   1   1]
 [ 20   0  -2   4   1]
 [ 20 -10  10  20   1]]
<class 'numpy.ndarray'>
int32
row:  3
col:  5
4
Total byte yang digunakan array A: 60


ARANGE dan RESHAPE

In [42]:
A=np.arange(1,65)
print(A)
A = A.reshape([8,8]) #reshape harus sesuai jumlah datanya
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


In [67]:
A = np.arange(5,61,5).reshape([3,4])
print(A, "\n")
B = np.arange(5,61,5).reshape([3,4])
print(B, "\n")
# A[:, -1] = 1
# print(A, "\n")

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]] 

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]] 



CONCATENATE

In [70]:
x = np.concatenate([A,B])
print(x, "\n")

x=np.concatenate([A,B], axis=1)
print(x, "\n")


[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]
 [ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]] 

[[ 5 10 15 20  5 10 15 20]
 [25 30 35 40 25 30 35 40]
 [45 50 55 60 45 50 55 60]] 



In [60]:
C = np.vstack([A,B])
D = np.hstack([A,B])
E = np.dstack([A,B])
print(C,"\n")
print(D,"\n")
print(E,"\n")

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]
 [ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]] 

[[ 5 10 15 20  5 10 15 20]
 [25 30 35 40 25 30 35 40]
 [45 50 55 60 45 50 55 60]] 

[[[ 5  5]
  [10 10]
  [15 15]
  [20 20]]

 [[25 25]
  [30 30]
  [35 35]
  [40 40]]

 [[45 45]
  [50 50]
  [55 55]
  [60 60]]] 



SPLIT

In [65]:
A = [1,2,3,99,999,3,2,1]
print(A)
A1,A2,A3 = np.split(A, [3,5]) #split pada index 3 dan index 5
print(A1, A2, A3)

[1, 2, 3, 99, 999, 3, 2, 1]
[1 2 3] [ 99 999] [3 2 1]


In [ ]:
A = np.arange(16).reshape(4,4)
print(A, "\n")
upper, lower = np.vsplit(A,[2]) #displit menjadi 2 secara vertical
print(upper,"\n")
print(lower,"\n")

left, right = np.hsplit(A, [2]) #displit menjadi 2 secara horizontal
print(left, "\n")
print(right, "\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 



UFuncs

In [85]:
X = np.linspace(0,10,50) #generate angka dari 0-10 berjumlah 50 angka decimal
print(X)
print(X.shape, "\n")

#semua data ditambah 1
X+=1
print(X, "\n")

Y = np.sin(X)
print(Y, "\n")

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
(50,) 

[ 1.          1.20408163  1.40816327  1.6122449   1.81632653  2.02040816
  2.2244898   2.42857143  2.63265306  2.83673469  3.04081633  3.24489796
  3.44897959  3.65306122  3.85714286  4.06122449  4.26530612  4.46938776
  4.67346939  4.87755102  5.08163265  5.28571429  5.48979592  5.69387755
  5.89795918  6.10204082  6.30612245  6.51020408  6.71428571  6.91836735
  7.12244898  7.3