NUMPY PART2

In [2]:
import numpy as np
print('ok')

ok


UFUNCTION

In [6]:
def hitung_volume(x,y,z):
    V =x*y*z
    L =2*(x*y + y*z +x*z)
    return V, L

x=[1,3,5,2]
y=[10,20,5,10]
z=[2,5,6,3]
V, L = np.frompyfunc(hitung_volume,3,2)(x,y,z) #ada 3 input dan 2 output
print(V,L)

[20 300 150 60] [64 350 170 112]


In [47]:
# np.random.seed(0) #untuk menghasilkan 1 array yg sama walaupun program di run beberapa kali
x = np.random.randint(10, size=(3, 4)) #array 2D
print(x) 

# how many values less than 6?
print(np.count_nonzero(x < 6))
print(np.count_nonzero(x < 6) and np.count_nonzero(x>3))

[[4 3 0 3]
 [5 0 2 3]
 [8 1 3 3]]
11
3


In [34]:
np.random.seed(0)
x = np.random.randint(10, size=(3,4))
print(x)
print("-"*10)
print(np.sum(x)) #menjumlahkan semua data di array x
print("-"*10)
print(np.sum(x, axis=0)) #menjumlahkan data pada masing-masing kolom/vertical
print("-"*10)
print(np.sum(x, axis=1)) #menjumlahkan data pada masing-masing row/horizontal
print("-"*10)
print(np.sum(x[::2], axis=1)) #menjumlahkan data array x pada kolom 0 sampai habis dengan interval 2 secara horizontal
print("-"*10)
print(np.sum(x<6, axis=1)) #menghitung berapa data yang valuenya kurang dari 6 secara horizontal
print("-"*10)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
----------
54
----------
[14 13 13 14]
----------
[11 24 19]
----------
[11 19]
----------
[4 2 2]
----------


In [53]:
np.random.seed(0)
x = np.random.randint(10, size=(3,4))
print(x)
print(np.any(x>8)) #TRUE/FALSE --> apakah ada data yang nilainya lebih dari 8 pada array x?
print(np.all(x>8)) #TRUE/FALSE --> apakah semua data nilainya lebih dari 8 pada array x?
print(np.all(x>5, axis=1)) #TRUE/FALSE --> apakah data pada semua row memiliki value di atas 5?
print(np.all(x[0:1:1,:]>5, axis=1)) #TRUE/FALSE --> apakah semua data pada baris 0 lebih besar dari 5 secara horizontal?
print(np.all(x[0:2:1,:]>5, axis=1)) #TRUE/FALSE --> apakah semua data pada baris 0 dan 1 lebih besar dari 5 secara horizontal?
print(np.any((x>3) & (x<6), axis=1)) #TRUE/FALSE --> apakah pada setiap baris ada data yang lebih besar dari 3 dan lebih kecil dari 6?
print(np.any(x%2==0, axis=0)) #TRUE/FALSE --> apakah pada setiap kolom ada data genap?
print(np.any(x%2==0, axis=1)) #TRUE/FALSE --> apakah pada setiap baris ada data genap?

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
True
False
[False False False]
[False]
[False False]
[ True  True  True]
[ True  True False  True]
[ True False  True]


FANCY INDEXING

In [ ]:
np.random.seed(0)
x - np.random.randint(10, size=(3,4))
print(x)

row = np.array([0,1,2])
col = np.array([2,1,3])
print(x[row,col]) #ambil data pada array x dengan data berindex [0,2], [1,1], dan[2,3]

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[3 9 6]
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [ ]:
np.random.seed(0)
x = np.random.randint(100, size=10)
print(x)

idx = [3,7,4]
print(x[idx]) #ambil data pada array x yang berindex angka pada array idx

[44 47 64 67 67  9 83 21 36 87]
[67 21 67]


In [64]:
np.random.seed(0)
x = np.random.randint(10, size=(3,4))
print(x, "\n")

row = np.array([0,1,2])
col = np.array([2,1,3])
#ambil semua data pada x dengan aturan semua data row dengan index array row, dan colom pada index data array col 
print(x[row[:,np.newaxis],col]) #np.newaxis untuk mempertahankan row
print()
print(x[row,col])
print()

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[[3 0 3]
 [3 9 5]
 [7 4 6]]

[3 9 6]



In [ ]:
x = np.arange(10)
print(x)
idx = np.array([2,1,8,4])
x[idx] = 99 #mengganti data-data pada array x dengan index sesuai pada data array idx, dan menggantinya dengan angka 99
print(x)

[0 1 2 3 4 5 6 7 8 9]
[ 0 99 99  3 99  5  6  7 99  9]


Sorting

In [69]:
x = np.array([2,1,4,3,5])
print(x)
print(np.sort(x)) #sorting pakai numpy
print(sorted(x)) #sorting pakai function, hasilnya jadi list
i = np.argsort(x) #sorting data dan yang otuputnya adalah hasil sorting dengan indexnya
print(i)

[2 1 4 3 5]
[1 2 3 4 5]
[1, 2, 3, 4, 5]
[1 0 3 2 4]


In [ ]:
np.random.seed(0)
x = np.random.randint(10, size=(3,4))
print(x,"\n")
print(np.sort(x, axis=1),"\n") #urutkan data tiap baris

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]] 

[[0 3 3 5]
 [3 5 7 9]
 [2 4 6 7]] 



PARTITION

In [75]:
x = np.array([7,2,3,1,6,5,4])
print(np.partition(x,3))
print(np.partition(x,4))
print(np.partition(x,5))

[2 1 3 4 6 5 7]
[2 1 3 4 5 6 7]
[2 1 3 4 5 6 7]


SEARCHING
- mencari data pada suatu array

In [78]:
a = np.array([1, 2, 3, 4, 5, 4, 4])
print(a)
x = np.where(a==4)
print(x)
x = np.where(a==1)
print(x)

[1 2 3 4 5 4 4]
(array([3, 5, 6], dtype=int64),)
(array([0], dtype=int64),)


In [ ]:
a = np.array([2,7,9,12,12])
print(a)
print(np.searchsorted(a,8)) #8 disisipkan ada index 2 agar array tetap tersorting, lalu print index tempatnya
print(np.searchsorted(a,10, side="right"))
print(np.searchsorted(a, [2,4,6,11]))

arr = np.array([41, 42, 43, 44])
x = arr[[True, False, True, False]]
print(x) # Output: [41 43]

[ 2  7  9 12 12]
2
3
[0 1 1 3]
[41 43]


FILTERING

In [82]:
a = np.array([2,7,9,12,12])
filter1 = a%2==0
print(filter1)
b = a[filter1]
print(b)

[ True False False  True  True]
[ 2 12 12]


LATIHAN SOAL
1. Buat Numpy 2D, MANUAL, angka bebas
2. Buat Numpy 2D, OTOMATIS dengan range 1-20 dan ukuran 4,5

In [83]:
manual = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(manual)

oto = np.random.randint(1,21, size=(4,5))
print(oto)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[13  2  7  8 15]
 [18  6 14  9 10]
 [20 17 20  6 16]
 [16  1 19  4 18]]


SOAL1: Angka ganjil diubah menjadi 1, angka genap diubah menjadi 2

In [86]:
np.random.seed(0)
oto = np.random.randint(1,21, size=(4,5))
print(oto)

filterGanjil = oto%2!=0
filterGenap = oto%2==0
oto[filterGanjil] = 1
oto[filterGenap] = 0
print(oto)

[[13 16  1  4  4]
 [ 8 10 20 19  5]
 [ 7 13  2  7  8]
 [15 18  6 14  9]]
[[1 0 1 0 0]
 [0 0 0 1 1]
 [1 1 0 1 0]
 [1 0 0 0 1]]


SOAL2: mengubah angka pada kolom terakhir menjadi -1

In [87]:
np.random.seed(0)
oto = np.random.randint(1,21, size=(4,5))
print(oto)

[[13 16  1  4  4]
 [ 8 10 20 19  5]
 [ 7 13  2  7  8]
 [15 18  6 14  9]]


SOAL3: Ubah array 2d ini sehingga setiap value pada sepanjang kolom dibaagi dengan nilai maksimalnya

In [101]:
np.random.seed(0)
oto = np.random.randint(1,21, size=(4,5))
print(oto)

max = np.max(oto, axis=1) #mencari nilai max pada setiap baris, dengan bentuk matrix baris
max = max.reshape(4,1) #menghubah nilai maksimum menjadi bentuk matrix olom
print(max)
oto1 = oto/max

print(oto1)

[[13 16  1  4  4]
 [ 8 10 20 19  5]
 [ 7 13  2  7  8]
 [15 18  6 14  9]]
[[16]
 [20]
 [13]
 [18]]
[[0.8125     1.         0.0625     0.25       0.25      ]
 [0.4        0.5        1.         0.95       0.25      ]
 [0.53846154 1.         0.15384615 0.53846154 0.61538462]
 [0.83333333 1.         0.33333333 0.77777778 0.5       ]]


SOAL4: Sepanjang kolom, yang minimum diubah menjadi angka 0, yang maximal diubah menjadi angka1, yang lain menyesuaikan

NOTED: proses ini dinamakan normalisasi fitur

In [117]:
np.random.seed(0)
oto = np.random.randint(1,21, size=(4,5))
print(oto)

min = np.min(oto, axis=1).reshape(4,1)
print(min)

max = np.max(oto, axis=1).reshape(4,1)
print(max)

new_data = ((oto-min)*(1-0)/(max-min)) + 0
print(new_data)

[[13 16  1  4  4]
 [ 8 10 20 19  5]
 [ 7 13  2  7  8]
 [15 18  6 14  9]]
[[1]
 [5]
 [2]
 [6]]
[[16]
 [20]
 [13]
 [18]]
[[0.8        1.         0.         0.2        0.2       ]
 [0.2        0.33333333 1.         0.93333333 0.        ]
 [0.45454545 1.         0.         0.45454545 0.54545455]
 [0.75       1.         0.         0.66666667 0.25      ]]
